depends_on:
    - lint
    - check-starting
    - freedesktop-check
    - check-data-files

steps:
    sourceforge_deploy:
        image: codeberg.org/jakobdev/python-ci-build-container:latest
        pull: true
        commands:
            - init-container
            - source set-file-env VERSION jdAppStreamEdit/version.txt
            - full-python-build --name jdAppStreamEdit --version $VERSION --copy-windows-exe ExternalReleasesEditor.exe
            - write-changelog-readme --name jdAppStreamEdit --version $VERSION --output-file Output/README.md
            - sourceforge-upload --upload-dir ./Output/ --project jdappstreamedit --version $VERSION --app-name jdAppStreamEdit --codeberg-release
        secrets: [SOURCEFORGE_USERNAME, SOURCEFORGE_PASSWORD, SOURCEFORGE_API_KEY, CODEBERG_API_TOKEN]

when:
    event: tag
